// Cloud save configuration
// To enable cloud saves via Supabase:
// 1. Sign up at https://supabase.com
// 2. Create a new project
// 3. Go to Project Settings → API → copy anon public key and URL
// 4. Set them below
// 5. Run this SQL in Supabase SQL editor:
//
// CREATE TABLE saves (
//   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   username text UNIQUE NOT NULL,
//   data jsonb NOT NULL DEFAULT '{}',
//   updated_at timestamptz DEFAULT now()
// );
//
// CREATE POLICY "users can read own save" ON saves
//   FOR SELECT USING (username = current_setting('app.username', true));
// CREATE POLICY "users can insert own save" ON saves
//   FOR INSERT WITH CHECK (username = current_setting('app.username', true));
// CREATE POLICY "users can update own save" ON saves
//   FOR UPDATE USING (username = current_setting('app.username', true));
//
// ALTER TABLE saves ENABLE ROW LEVEL SECURITY;

const CLOUD_CONFIG = {
  enabled: false,
  supabaseUrl: 'https://your-project.supabase.co',
  supabaseAnonKey: 'your-anon-key',
};

let _supabase = null;

function initCloud() {
  if (!CLOUD_CONFIG.enabled) return;
  try {
    const { createClient } = supabase;
    _supabase = createClient(CLOUD_CONFIG.supabaseUrl, CLOUD_CONFIG.supabaseAnonKey);
  } catch(e) {
    console.log('Supabase init failed:', e);
    _supabase = null;
  }
}

async function cloudSave() {
  if (!_supabase || !USER || !G) return false;
  if (!isSubActive()) return false;
  try {
    const data = JSON.parse(JSON.stringify(G));
    const { error } = await _supabase
      .from('saves')
      .upsert({ username: USER, data, updated_at: new Date().toISOString() }, { onConflict: 'username' });
    if (error) throw error;
    return true;
  } catch(e) {
    console.log('Cloud save failed:', e);
    return false;
  }
}

async function cloudLoad() {
  if (!_supabase || !USER) return null;
  try {
    const { data, error } = await _supabase
      .from('saves')
      .select('data, updated_at')
      .eq('username', USER)
      .single();
    if (error || !data) return null;
    return { data: data.data, updatedAt: data.updated_at };
  } catch(e) {
    console.log('Cloud load failed:', e);
    return null;
  }
}

function hasCloudConflict(local, cloud) {
  if (!cloud) return false;
  const localTime = local.lastSave || 0;
  const cloudTime = new Date(cloud.updatedAt).getTime();
  return cloudTime > localTime + 5000;
}

async function syncCloud() {
  if (!_supabase || !USER || !G) return;
  if (!isSubActive()) return;

  const cloud = await cloudLoad();
  if (!cloud) {
    await cloudSave();
    return;
  }

  if (hasCloudConflict(G, cloud)) {
    const localDm = G.prest.dm || 0;
    const cloudDm = cloud.data.prest?.dm || 0;
    if (cloudDm > localDm) {
      // Cloud is ahead, use it
      const pw = G._pw;
      const sub = G._subActive;
      G = Object.assign(freshState(), cloud.data);
      migrateState(G);
      G._pw = pw;
      G._subActive = sub;
      toast('Cloud save restored (ahead of local)', 'info');
      rebuildUI();
    }
  }

  await cloudSave();
}
